# Generated by Django 4.2.5 on 2023-10-01 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rideshare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='accepted',
            field=models.BooleanField(default=False),
        ),
    ]
